# Generated by Django 5.0 on 2023-12-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pratas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='imagens_produtos/'),
        ),
    ]
