# Generated by Django 5.0 on 2023-12-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pratas', '0005_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
